// --Signup
export const SIGNUP_REQUSET = 'SIGNUP_REQUSET';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

// Set user Data in DB
export const SET_USER_DATA_REQUEST = 'SET_USER_DATA_REQUEST';

// --Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// --Add Patient
export const ADD_PATIENT_REQUEST = 'ADD_PATIENT_REQUEST';
export const ADD_PATIENT_SUCCESS = 'ADD_PATIENT_SUCCESS';
export const ADD_PATIENT_ERROR = 'ADD_PATIENT_ERROR';

// -get Patient

export const GET_PATEINT_REQUEST="GET_PATEINT_REQUEST"
export const GET_PATEINT_SUCCESS="GET_PATEINT_SUCCESS"
export const GET_PATEINT_ERROR="GET_PATEINT_ERROR"


// -delete Patient

export const DEL_PATEINT_REQUEST="DEL_PATEINT_REQUEST"
export const DEL_PATEINT_SUCCESS="DEL_PATEINT_SUCCESS"
export const DEL_PATEINT_ERROR="DEL_PATEINT_ERROR"